### ISSUE TITLE
SI4703.h

### ISSUE THREAD

**Issue by fungreenfox** [csdexter/Si4703#1]
In SI4703.h there is a reference to calling WProgram.h.
This is not present anywhere, and a search for it, gives this :

Now, that WProgram.h, is a definition file created by and for the wiring project and board. That's why it has a W on it. It has been in Arduino IDE since its beginning and was replaced by Arduino.h only recently when Arduino 1.0 was released. Now all Arduino 1.0+ IDE will use Arduino.h and not WProgram.h so if you have that plus some other old stuff, you will have to make changes to work with Arduino 1.0+ IDE.

Do you expect the client to delete this reference and add arduino.h?

**Comment by csdexter** [comment]
Hello and thanks for the bug report.

If you look into `Si4703.h`, at line 16, you will notice there are preprocessor directives there that control whether `WProgram.h` or `Arduino.h` is included, depending on the detected compilation environment.

If compiling the library in the Arduino environment, `Arduino.h` will be automatically selected.

Does this answer your question?

**Comment by fungreenfox** [comment]
Yes, Thank You.
